### PR TITLE
21 implement page switching between catalog and dashboard

### PR DESCRIPTION
**Pull request by zakaBouj**

### CODE REVIEW

**Comment by zakaBouj** [comment]
# How it works
### NavigationBar

The **NavigationBar** is a custom component extending `JComponent` that provides simple navigation controls for switching between different pages in the application. This component relies on a reference to the `MainPanel` to call its `showPage(...)` method, which changes the visible page in the center area of the main window.

1. **Purpose**
    - The `NavigationBar` is responsible for rendering a simple horizontal bar with buttons that allow the user to navigate between two pages: the “Catalog” page and the “Dashboard” page.
2. **Key Responsibilities**
    - Provide user interface elements (buttons) that trigger page switches in the `MainPanel`.
    - Invoke `mainPanel.showPage(...)` with the appropriate page constants (e.g., `PAGE_CATALOG`, `PAGE_DASHBOARD`) to change which page is displayed.
3. **Constructor and Layout**
    - **Constructor**
        
        ```java
        public NavigationBar(MainPanel mainPanel) {
            setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
            ...
        }
        
        ```
        
        - Receives a reference to the `MainPanel` through its constructor. This is essential for the NavigationBar to communicate back to the main UI and switch pages.
        - Uses a `BoxLayout` oriented along the X-axis (`BoxLayout.X_AXIS`) to lay out the buttons horizontally.
4. **UI Elements and Event Handling**
    - **Catalog Button**
        
        ```java
        JButton catalogButton = new JButton("Catalog");
        catalogButton.addActionListener(e -> mainPanel.showPage(MainPanel.PAGE_CATALOG));
        
        ```
        
        - When clicked, it calls `mainPanel.showPage(...)`, instructing the `MainPanel` to display the **DroneCatalog** page.
    - **Dashboard Button**
        
        ```java
        JButton dashboardButton = new JButton("Dashboard");
        dashboardButton.addActionListener(e -> mainPanel.showPage(MainPanel.PAGE_DASHBOARD));
        
        ```
        
        - When clicked, it calls `mainPanel.showPage(...)`, instructing the `MainPanel` to display the **DroneDashboard** page.
   
5. **Integration with MainPanel**
    - The `NavigationBar` requires the `MainPanel` reference to function. It must be added to the UI (e.g., through the `NorthPanel`) in a way that ensures `MainPanel` is passed in at construction time.
    - The `MainPanel` itself manages the layout (using a `CardLayout`) and switches visible pages based on requests from the `NavigationBar`.
6. **Example Usage**
    
    ```java
    // In MainPanel.java or NorthPanel.java
    NavigationBar navigationBar = new NavigationBar(this);
    add(navigationBar);
    
    ```
    
    By passing `this` (the `MainPanel` instance) to the `NavigationBar`, the navigation buttons gain the ability to directly invoke page switches.

**Comment by zakaBouj** [comment]
# How it works
### NavigationBar Version https://github.com/Code-Hauptwache/DroneDeck/pull/36/commits/4e5e3e5763e4c32c841fc6ab64588dcec74f0212

The **NavigationBar** is a custom component extending `JComponent` that provides simple navigation controls for switching between different pages in the application. This component relies on a reference to the `MainPanel` to call its `showPage(...)` method, which changes the visible page in the center area of the main window.

1. **Purpose**
    - The `NavigationBar` is responsible for rendering a simple horizontal bar with buttons that allow the user to navigate between two pages: the “Catalog” page and the “Dashboard” page.
2. **Key Responsibilities**
    - Provide user interface elements (buttons) that trigger page switches in the `MainPanel`.
    - Invoke `mainPanel.showPage(...)` with the appropriate page constants (e.g., `PAGE_CATALOG`, `PAGE_DASHBOARD`) to change which page is displayed.
3. **Constructor and Layout**
    - **Constructor**
        
        ```java
        public NavigationBar(MainPanel mainPanel) {
            setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
            ...
        }
        
        ```
        
        - Receives a reference to the `MainPanel` through its constructor. This is essential for the NavigationBar to communicate back to the main UI and switch pages.
        - Uses a `BoxLayout` oriented along the X-axis (`BoxLayout.X_AXIS`) to lay out the buttons horizontally.
4. **UI Elements and Event Handling**
    - **Catalog Button**
        
        ```java
        JButton catalogButton = new JButton("Catalog");
        catalogButton.addActionListener(e -> mainPanel.showPage(MainPanel.PAGE_CATALOG));
        
        ```
        
        - When clicked, it calls `mainPanel.showPage(...)`, instructing the `MainPanel` to display the **DroneCatalog** page.
    - **Dashboard Button**
        
        ```java
        JButton dashboardButton = new JButton("Dashboard");
        dashboardButton.addActionListener(e -> mainPanel.showPage(MainPanel.PAGE_DASHBOARD));
        
        ```
        
        - When clicked, it calls `mainPanel.showPage(...)`, instructing the `MainPanel` to display the **DroneDashboard** page.
   
5. **Integration with MainPanel**
    - The `NavigationBar` requires the `MainPanel` reference to function. It must be added to the UI (e.g., through the `NorthPanel`) in a way that ensures `MainPanel` is passed in at construction time.
    - The `MainPanel` itself manages the layout (using a `CardLayout`) and switches visible pages based on requests from the `NavigationBar`.
6. **Example Usage**
    
    ```java
    // In MainPanel.java or NorthPanel.java
    NavigationBar navigationBar = new NavigationBar(this);
    add(navigationBar);
    
    ```
    
    By passing `this` (the `MainPanel` instance) to the `NavigationBar`, the navigation buttons gain the ability to directly invoke page switches.

**Comment by zakaBouj** [comment]
I have Implemented the NavBar and added it to the [Milestones](https://www.notion.so/zakabouj/DroneDeck-Documentation-152408e5d09b800bb222fb4f9c63cec0?pvs=4#164408e5d09b80b19d9ec2c51186ba5b) i also explained in a [comment ](https://github.com/Code-Hauptwache/DroneDeck/pull/36#issuecomment-2558451542) here how the NavBar works, in case you want to add that to the Documentation @Gord310.

**Review by Gord310 — COMMENTED** [review]
Its seems like #41 is based upon this branch and not the main branch so my comments there also apply here. 

Some Docs would be better suited for the Class itself and some constructors have inadequate Docs (like docs wich dont mention the parameters)

But I didn't find anything wich isn't also in the #41 pull requst but correct me if thats not true.

**Pull request merged**
